# Neo4j second vector baseline

Node-embedding retrieval baseline with evaluation against `annotaion_q_graph` gold in canonical triple space.

Output CSV: `qnum,f1`.

In [48]:
%pip -q install python-dotenv

from dotenv import load_dotenv
import os

load_dotenv(".env")   # подхватит /.../neo4j_граф/.env

DEEPSEEK_API_KEY = os.getenv("DEEPSEEK_API_KEY")
DEEPSEEK_API_KEY = os.getenv("GPT_API_KEY")

print("DEEPSEEK_API_KEY loaded:", bool(DEEPSEEK_API_KEY))

Note: you may need to restart the kernel to use updated packages.
DEEPSEEK_API_KEY loaded: True

In [59]:
# 1) Imports and config

import os
import re
import json
import time
from pathlib import Path
from statistics import mean, median

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry
import pandas as pd
from neo4j import GraphDatabase

BASE_DIR = Path('/Users/i.sharganov/🟩🟩🟩/обучение/МАГА/мага_обучение/3_сем/Диплом/эксперимент/neo4j_граф')
ANNOT_QG_DIR = BASE_DIR / 'annotaion_q_graph'
OUT_CSV_PATH = BASE_DIR / 'retrieval_outputs' / 'node_embedding_baseline_f1.csv'

NEO4J_URI = os.getenv('NEO4J_URI', 'bolt://localhost:7689')
NEO4J_USER = os.getenv('NEO4J_USER', 'neo4j')
NEO4J_PASSWORD = os.getenv('NEO4J_PASSWORD', '12345678')

OPENAI_API_KEY = os.getenv('OPENAI_API_KEY') or os.getenv('GPT_API_KEY')

QNUMS = [i for i in range (1, 102)]

NODE_EMB_MODEL = os.getenv('NODE_EMB_MODEL', 'text-embedding-3-small')
QUERY_EMB_MODEL = os.getenv('QUERY_EMB_MODEL', 'text-embedding-3-small')
EMB_DIM = int(os.getenv('EMB_DIM', '1536'))

TOP_N_NODES = int(os.getenv('TOP_N_NODES', '25'))
HOPS = int(os.getenv('HOPS', '2'))
MAX_TRIPLES = int(os.getenv('MAX_TRIPLES', '5000'))
USE_CANONICAL_EVAL = True

TARGET_LABELS = [
    'Encounter', 'DocumentCheck', 'DocumentInstance', 'Questioning',
    'BiometricCheck', 'City', 'Airport', 'Country'
]

EMB_BATCH_SIZE = int(os.getenv('EMB_BATCH_SIZE', '16'))
WRITE_BATCH_SIZE = int(os.getenv('WRITE_BATCH_SIZE', '200'))
SKIP_EXISTING_EMBEDDINGS = True

META_KEYS = [
    'intents', 'mode', 'conditional', 'scope', 'exclude_scope',
    'doc_types', 'topic_keys', 'biometric_modalities', 'aggregate'
]

print('ANNOT_QG_DIR =', ANNOT_QG_DIR)
print('OUT_CSV_PATH =', OUT_CSV_PATH)
print('QNUMS =', QNUMS)

ANNOT_QG_DIR = /Users/i.sharganov/🟩🟩🟩/обучение/МАГА/мага_обучение/3_сем/Диплом/эксперимент/neo4j_граф/annotaion_q_graph
OUT_CSV_PATH = /Users/i.sharganov/🟩🟩🟩/обучение/МАГА/мага_обучение/3_сем/Диплом/эксперимент/neo4j_граф/retrieval_outputs/node_embedding_baseline_f1.csv
QNUMS = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101]

In [60]:
# 2) Core clients and low-level helpers

def require_env():
    if not OPENAI_API_KEY:
        raise ValueError('OPENAI_API_KEY or GPT_API_KEY is not set')
    if not NEO4J_PASSWORD:
        raise ValueError('NEO4J_PASSWORD is not set')


def get_driver():
    return GraphDatabase.driver(NEO4J_URI, auth=(NEO4J_USER, NEO4J_PASSWORD))


def _requests_session():
    retry = Retry(
        total=5,
        connect=5,
        read=5,
        backoff_factor=1.0,
        status_forcelist=[408, 409, 425, 429, 500, 502, 503, 504],
        allowed_methods=frozenset(['POST']),
        raise_on_status=False,
    )
    sess = requests.Session()
    adapter = HTTPAdapter(max_retries=retry, pool_connections=20, pool_maxsize=20)
    sess.mount('https://', adapter)
    sess.mount('http://', adapter)
    return sess


def neo4j_query(driver, query, params=None):
    with driver.session() as session:
        res = session.run(query, params or {})
        return [dict(r) for r in res]


def embed_texts(texts, model):
    if not texts:
        return []

    all_vectors = []
    session = _requests_session()
    try:
        for batch in chunks(texts, EMB_BATCH_SIZE):
            payload = {
                'model': model,
                'input': batch,
            }

            last_err = None
            for attempt in range(1, 7):
                try:
                    resp = session.post(
                        'https://api.openai.com/v1/embeddings',
                        headers={
                            'Authorization': f'Bearer {OPENAI_API_KEY}',
                            'Content-Type': 'application/json',
                        },
                        json=payload,
                        timeout=(20, 180),
                    )
                    if resp.ok:
                        data = resp.json().get('data', [])
                        data = sorted(data, key=lambda x: x['index'])
                        vecs = [d['embedding'] for d in data]
                        if len(vecs) != len(batch):
                            raise RuntimeError(f'Embeddings size mismatch: got {len(vecs)}, expected {len(batch)}')
                        all_vectors.extend(vecs)
                        last_err = None
                        break

                    body = ''
                    try:
                        body = resp.text[:800]
                    except Exception:
                        body = '<no-body>'
                    if resp.status_code in {408, 409, 425, 429, 500, 502, 503, 504}:
                        last_err = RuntimeError(f'Retriable API error {resp.status_code}: {body}')
                    else:
                        raise RuntimeError(f'Embeddings API error {resp.status_code}: {body}')

                except requests.exceptions.SSLError as e:
                    last_err = e
                except requests.exceptions.ConnectionError as e:
                    last_err = e
                except requests.exceptions.Timeout as e:
                    last_err = e

                if attempt < 6:
                    sleep_sec = min(20, (2 ** (attempt - 1)))
                    time.sleep(sleep_sec)
                else:
                    raise RuntimeError(f'Embeddings failed after retries: {last_err}')

            if last_err is not None:
                raise RuntimeError(f'Embeddings failed for batch: {last_err}')
    finally:
        session.close()

    return all_vectors


def chunks(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i+n]


def _extract_post_id_from_key(value: str):
    if not value or not isinstance(value, str):
        return None
    m = re.search(r'encounter_(\d+)', value)
    if m:
        return m.group(1)
    m = re.search(r'questioning_encounter_(\d+)', value)
    if m:
        return m.group(1)
    m = re.search(r'doccheck_encounter_(\d+)', value)
    if m:
        return m.group(1)
    m = re.search(r'documentinstance_encounter_(\d+)', value)
    if m:
        return m.group(1)
    return None

In [61]:
# 3) Gold loading and canonicalization (compatible with neo4j_sem_rag)

def annotation_files_for_qnum(qnum: int):
    qdir = ANNOT_QG_DIR / f'q_{qnum}'
    if not qdir.exists():
        raise FileNotFoundError(f'Question directory not found: {qdir}')
    files = sorted(qdir.glob('*/*.json'))
    ann = [f for f in files if f.name.startswith('annotation_') and f.suffix == '.json']
    return ann


def get_question_text(qnum: int) -> str:
    files = annotation_files_for_qnum(qnum)
    if not files:
        raise ValueError(f'No annotation files found for q_{qnum}')
    data = json.loads(files[0].read_text(encoding='utf-8'))
    question = data.get('question')
    if not question:
        raise ValueError(f'Question text not found in {files[0]}')
    return question


def load_gold(qnum: int):
    qdir = ANNOT_QG_DIR / f'q_{qnum}'
    triples = []
    metas = []
    for f in annotation_files_for_qnum(qnum):
        data = json.loads(f.read_text(encoding='utf-8'))
        for t in data.get('triples', []):
            s = t.get('s', {})
            o = t.get('o', {})
            triples.append((s.get('label'), s.get('key'), t.get('p'), o.get('label'), o.get('key')))
        meta = {k: data.get(k) for k in META_KEYS if k in data}
        if meta:
            metas.append(meta)
    meta_ref = metas[0] if metas else {}
    meta_consistent = all(m == meta_ref for m in metas) if metas else True

    agg_ref = None
    agg_path = qdir / 'aggregate_output.json'
    if agg_path.exists():
        agg_ref = json.loads(agg_path.read_text(encoding='utf-8'))

    return set(triples), meta_ref, meta_consistent, agg_ref


def _canonical_post_key_from_annotation(data: dict):
    for t in data.get('triples', []):
        for side in ['s', 'o']:
            key = (t.get(side) or {}).get('key')
            post_id = _extract_post_id_from_key(key)
            if post_id:
                return f'post_{post_id}'
    return None


def load_gold_canonical(qnum: int):
    canonical = set()
    encounters = {}
    _, meta_ref, _, agg_ref = load_gold(qnum)

    for f in annotation_files_for_qnum(qnum):
        data = json.loads(f.read_text(encoding='utf-8'))
        post_key = _canonical_post_key_from_annotation(data)
        if not post_key:
            continue
        enc = encounters.setdefault(post_key, {
            'post_key': post_key,
            'atCountry': set(),
            'atCity': set(),
            'atAirport': set(),
            'document_types': set(),
            'topic_keys': set(),
            'biometric_modalities': set(),
        })
        for t in data.get('triples', []):
            s = t.get('s', {})
            o = t.get('o', {})
            p = t.get('p')
            if s.get('label') == 'Encounter' and p in {'atCountry', 'atCity', 'atAirport'}:
                canonical.add((s.get('label'), post_key, p, o.get('label'), o.get('key')))
                if p == 'atCountry':
                    enc['atCountry'].add(o.get('key'))
                elif p == 'atCity':
                    enc['atCity'].add(o.get('key'))
                elif p == 'atAirport':
                    enc['atAirport'].add(o.get('key'))
            elif p == 'documentType' and o.get('key'):
                canonical.add(('Encounter', post_key, 'documentType', 'Literal', o.get('key')))
                enc['document_types'].add(o.get('key'))
            elif p == 'topicKey' and o.get('key'):
                canonical.add(('Encounter', post_key, 'topicKey', 'Literal', o.get('key')))
                enc['topic_keys'].add(o.get('key'))
            elif p == 'biometricModality' and o.get('key'):
                canonical.add(('Encounter', post_key, 'biometricModality', 'Literal', o.get('key')))
                enc['biometric_modalities'].add(o.get('key'))

    return canonical, encounters, meta_ref, agg_ref

In [62]:
# 4) Node text representation and embedding build

def _vector_index_name(label: str) -> str:
    return f'vec_{label.lower()}_embedding'


def ensure_vector_indexes(driver, emb_dim: int = EMB_DIM):
    for label in TARGET_LABELS:
        idx_name = _vector_index_name(label)
        q = f"""
        CREATE VECTOR INDEX {idx_name} IF NOT EXISTS
        FOR (n:`{label}`) ON (n.embedding)
        OPTIONS {{indexConfig: {{`vector.dimensions`: {emb_dim}, `vector.similarity_function`: 'cosine'}}}}
        """
        neo4j_query(driver, q)


def fetch_nodes_for_embedding(driver, limit=None, skip_existing: bool = True):
    where_emb = 'AND n.embedding IS NULL' if skip_existing else ''
    lim = f'LIMIT {int(limit)}' if limit else ''
    q = f"""
    MATCH (n)
    WHERE any(l IN labels(n) WHERE l IN $labels)
      AND n.key IS NOT NULL
      {where_emb}
    RETURN id(n) AS nid, labels(n) AS labels, properties(n) AS props
    {lim}
    """
    return neo4j_query(driver, q, {'labels': TARGET_LABELS})


def fetch_node_context(driver, nid: int):
    q = """
    MATCH (n) WHERE id(n) = $nid
    OPTIONAL MATCH (n)-[r]-(m)
    RETURN collect(DISTINCT type(r))[0..20] AS rel_types,
           collect(DISTINCT coalesce(head(labels(m)), '') + ':' + coalesce(m.key, ''))[0..20] AS neighbors
    """
    rows = neo4j_query(driver, q, {'nid': nid})
    if not rows:
        return {'rel_types': [], 'neighbors': []}
    return rows[0]


def node_to_text(node_row, ctx):
    labels = ','.join(node_row.get('labels') or [])
    props = dict(node_row.get('props') or {})
    key = props.get('key', '')
    props.pop('embedding', None)

    scalar_props = []
    for k, v in sorted(props.items()):
        if k == 'key':
            continue
        if isinstance(v, (str, int, float, bool)):
            scalar_props.append(f'{k}={v}')

    rel_types = ', '.join(x for x in (ctx.get('rel_types') or []) if x)
    neighbors = ', '.join(x for x in (ctx.get('neighbors') or []) if x)

    return (
        f'labels: {labels}\n'
        f'key: {key}\n'
        f'properties: {'; '.join(scalar_props)}\n'
        f'relations: {rel_types}\n'
        f'neighbors: {neighbors}'
    )


def write_node_embeddings(driver, rows):
    if not rows:
        return
    q = """
    UNWIND $rows AS row
    MATCH (n) WHERE id(n) = row.nid
    SET n.embedding = row.embedding
    """
    neo4j_query(driver, q, {'rows': rows})


def build_node_embeddings(limit=None, overwrite=False):
    require_env()
    with get_driver() as driver:
        ensure_vector_indexes(driver, emb_dim=EMB_DIM)
        nodes = fetch_nodes_for_embedding(driver, limit=limit, skip_existing=(SKIP_EXISTING_EMBEDDINGS and not overwrite))
        print('nodes_to_embed =', len(nodes))

        prepared = []
        for row in nodes:
            ctx = fetch_node_context(driver, row['nid'])
            prepared.append({
                'nid': row['nid'],
                'text': node_to_text(row, ctx),
            })

        t0 = time.time()
        written = 0
        for text_batch in chunks(prepared, EMB_BATCH_SIZE):
            vectors = embed_texts([x['text'] for x in text_batch], model=NODE_EMB_MODEL)
            out_rows = [
                {'nid': text_batch[i]['nid'], 'embedding': vectors[i]}
                for i in range(len(text_batch))
            ]
            for wbatch in chunks(out_rows, WRITE_BATCH_SIZE):
                write_node_embeddings(driver, wbatch)
                written += len(wbatch)

        print('embedded_written =', written)
        print('elapsed_sec =', round(time.time() - t0, 2))

In [63]:
# 5) Vector retrieval + hop expansion + canonical triple construction

def get_existing_vector_indexes(driver):
    q = """
    SHOW INDEXES
    YIELD name, type
    WHERE type = 'VECTOR'
    RETURN collect(name) AS names
    """
    rows = neo4j_query(driver, q)
    names = set(rows[0]['names']) if rows else set()
    return names


def query_seed_nodes(driver, question: str, top_n: int = TOP_N_NODES):
    qvec = embed_texts([question], model=QUERY_EMB_MODEL)[0]
    existing = get_existing_vector_indexes(driver)

    scored = {}
    k_each = max(top_n, 1)
    for label in TARGET_LABELS:
        idx = _vector_index_name(label)
        if idx not in existing:
            continue
        q = """
        CALL db.index.vector.queryNodes($index_name, $k, $embedding)
        YIELD node, score
        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score
        """
        rows = neo4j_query(driver, q, {'index_name': idx, 'k': k_each, 'embedding': qvec})
        for r in rows:
            nid = r['nid']
            if nid not in scored or r['score'] > scored[nid]['score']:
                scored[nid] = r

    ranked = sorted(scored.values(), key=lambda x: -float(x['score']))[:top_n]
    return ranked


def expand_node_ids(driver, seed_ids, hops: int = HOPS):
    if not seed_ids:
        return []
    hops = max(0, int(hops))
    q = f"""
    MATCH (s) WHERE id(s) IN $seed_ids
    MATCH p=(s)-[*0..{hops}]-(n)
    RETURN collect(DISTINCT id(n)) AS node_ids
    """
    rows = neo4j_query(driver, q, {'seed_ids': seed_ids})
    if not rows:
        return []
    return rows[0].get('node_ids') or []


def fetch_encounter_facts_from_node_ids(driver, node_ids):
    if not node_ids:
        return {}
    q = """
    MATCH (e:Encounter)
    WHERE id(e) IN $node_ids

    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)
    OPTIONAL MATCH (e)-[:atCity]->(ci:City)
    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)

    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)
    OPTIONAL MATCH (di)-[:documentType]->(dt)

    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)
    OPTIONAL MATCH (q)-[:topicKey]->(tk)

    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)
    OPTIONAL MATCH (b)-[:biometricModality]->(bm)

    RETURN e.key AS encounter_key,
           collect(DISTINCT co.key) AS countries,
           collect(DISTINCT ci.key) AS cities,
           collect(DISTINCT ap.key) AS airports,
           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,
           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,
           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios
    """
    rows = neo4j_query(driver, q, {'node_ids': node_ids})

    encounters = {}
    for r in rows:
        ekey = r.get('encounter_key')
        pid = _extract_post_id_from_key(ekey)
        if not pid:
            continue
        post_key = f'post_{pid}'
        encounters[post_key] = {
            'post_key': post_key,
            'atCountry': set(x for x in (r.get('countries') or []) if x),
            'atCity': set(x for x in (r.get('cities') or []) if x),
            'atAirport': set(x for x in (r.get('airports') or []) if x),
            'document_types': set(x for x in (r.get('docs') or []) if x),
            'topic_keys': set(x for x in (r.get('topics') or []) if x),
            'biometric_modalities': set(x for x in (r.get('bios') or []) if x),
        }
    return encounters


def encounter_rows_to_canonical_triples(encounter_rows):
    triples = set()
    for rec in encounter_rows.values():
        post_key = rec['post_key']
        for x in sorted(rec['atCountry']):
            triples.add(('Encounter', post_key, 'atCountry', 'Country', x))
        for x in sorted(rec['atCity']):
            triples.add(('Encounter', post_key, 'atCity', 'City', x))
        for x in sorted(rec['atAirport']):
            triples.add(('Encounter', post_key, 'atAirport', 'Airport', x))
        for x in sorted(rec['document_types']):
            triples.add(('Encounter', post_key, 'documentType', 'Literal', x))
        for x in sorted(rec['topic_keys']):
            triples.add(('Encounter', post_key, 'topicKey', 'Literal', x))
        for x in sorted(rec['biometric_modalities']):
            triples.add(('Encounter', post_key, 'biometricModality', 'Literal', x))
    return triples


def retrieve_canonical_triples_by_qnum(qnum: int, top_n_nodes: int = TOP_N_NODES, hops: int = HOPS):
    question = get_question_text(qnum)
    with get_driver() as driver:
        seeds = query_seed_nodes(driver, question, top_n=top_n_nodes)
        seed_ids = [r['nid'] for r in seeds]
        expanded_ids = expand_node_ids(driver, seed_ids, hops=hops)
        encounters = fetch_encounter_facts_from_node_ids(driver, expanded_ids)

    triples = encounter_rows_to_canonical_triples(encounters)
    if MAX_TRIPLES and len(triples) > MAX_TRIPLES:
        triples = set(list(sorted(triples))[:MAX_TRIPLES])

    return {
        'question': question,
        'seeds': seeds,
        'seed_ids': seed_ids,
        'expanded_ids': expanded_ids,
        'encounters': encounters,
        'triples': triples,
    }

In [64]:
# 6) Evaluation and CSV report (qnum,f1)

def f1_from_sets(pred_set, gold_set):
    tp = len(pred_set & gold_set)
    if not pred_set and not gold_set:
        return 1.0, 1.0, 1.0
    precision = tp / len(pred_set) if pred_set else 0.0
    recall = tp / len(gold_set) if gold_set else 0.0
    f1 = (2 * precision * recall / (precision + recall)) if (precision + recall) else 0.0
    return precision, recall, f1


def run_eval_qnum(qnum: int, print_details: bool = True):
    pred = retrieve_canonical_triples_by_qnum(qnum)
    gold_canonical, _, _, _ = load_gold_canonical(qnum)

    precision, recall, f1 = f1_from_sets(pred['triples'], gold_canonical)

    if print_details:
        print('qnum', qnum)
        print('question', pred['question'])
        print('seed_nodes', len(pred['seed_ids']))
        print('expanded_nodes', len(pred['expanded_ids']))
        print('retrieved', len(pred['triples']))
        print('gold', len(gold_canonical))
        print('precision', precision)
        print('recall', recall)
        print('f1', f1)

    return {'qnum': int(qnum), 'f1': float(f1)}


def run_eval_batch(qnums, out_csv: Path = OUT_CSV_PATH, print_details: bool = True):
    rows = []
    for q in qnums:
        rows.append(run_eval_qnum(int(q), print_details=print_details))

    df = pd.DataFrame(rows, columns=['qnum', 'f1']).sort_values('qnum').reset_index(drop=True)
    out_csv.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(out_csv, index=False, encoding='utf-8')

    print('saved_csv =', out_csv)
    print('n_questions =', len(df))
    if len(df):
        print('mean_f1 =', float(df['f1'].mean()))
        print('median_f1 =', float(df['f1'].median()))

    return df

In [65]:
# 7) Run cells

# One-time indexing/build (can be long):
require_env()
build_node_embeddings(limit=None, overwrite=False)

# Smoke test:
smoke_df = run_eval_batch([1], print_details=True)
smoke_df

# Full run by configured QNUMS:
result_df = run_eval_batch(QNUMS, out_csv=OUT_CSV_PATH, print_details=True)
result_df

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=6, column=12, offset=133>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 133, 'line': 6, 'column': 12}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (n)\n    WHERE any(l IN labels(n) WHERE l IN $labels)\n      AND n.key IS NOT NULL\n      AND n.embedding IS NULL\n    RETURN id(n) AS nid, labels(n) AS labels, properties(n) AS props\n    \n    '

nodes_to_embed = 0
embedded_written = 0
elapsed_sec = 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 1
question Which documents do I need to bring to passport control in Paris?
seed_nodes 25
expanded_nodes 280
retrieved 499
gold 299
precision 0.561122244488978
recall 0.9364548494983278
f1 0.7017543859649124
saved_csv = /Users/i.sharganov/🟩🟩🟩/обучение/МАГА/мага_обучение/3_сем/Диплом/эксперимент/neo4j_граф/retrieval_outputs/node_embedding_baseline_f1.csv
n_questions = 1
mean_f1 = 0.7017543859649124
median_f1 = 0.7017543859649124

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 1
question Which documents do I need to bring to passport control in Paris?
seed_nodes 25
expanded_nodes 280
retrieved 499
gold 299
precision 0.561122244488978
recall 0.9364548494983278
f1 0.7017543859649124

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 2
question Which documents do I need to bring to passport control in France?
seed_nodes 25
expanded_nodes 266
retrieved 499
gold 482
precision 0.9078156312625251
recall 0.9398340248962656
f1 0.9235474006116209

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 3
question Which question topics are most common at passport control in France?
seed_nodes 25
expanded_nodes 337
retrieved 559
gold 127
precision 0.1967799642218247
recall 0.8661417322834646
f1 0.32069970845481055

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 4
question In which country are the most documents requested?
seed_nodes 25
expanded_nodes 156
retrieved 130
gold 1493
precision 0.8615384615384616
recall 0.07501674480910918
f1 0.13801601971657426

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 5
question In which city in France is a return ticket requested most often?
seed_nodes 25
expanded_nodes 701
retrieved 503
gold 226
precision 0.23260437375745527
recall 0.5176991150442478
f1 0.32098765432098764

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 6
question How often are fingerprints taken when entering France?
seed_nodes 25
expanded_nodes 172
retrieved 158
gold 22
precision 0.02531645569620253
recall 0.18181818181818182
f1 0.044444444444444446

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 7
question What documents are checked at passport control and what questions are asked in Paris?
seed_nodes 25
expanded_nodes 314
retrieved 499
gold 331
precision 0.5951903807615231
recall 0.8972809667673716
f1 0.7156626506024096

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 8
question Which documents are checked in Paris, but not in Nice?
seed_nodes 25
expanded_nodes 275
retrieved 495
gold 299
precision 0.5656565656565656
recall 0.9364548494983278
f1 0.7052896725440807

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 9
question Which documents are checked for travelers who were asked about cash amount in France?
seed_nodes 25
expanded_nodes 334
retrieved 496
gold 29
precision 0.04233870967741935
recall 0.7241379310344828
f1 0.07999999999999999

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 10
question Which question topics are asked of travelers whose visa was checked in France?
seed_nodes 25
expanded_nodes 333
retrieved 559
gold 47
precision 0.07871198568872988
recall 0.9361702127659575
f1 0.14521452145214522

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 11
question Show document checks and question topics for the same encounters in Paris.
seed_nodes 25
expanded_nodes 331
retrieved 496
gold 133
precision 0.21169354838709678
recall 0.7894736842105263
f1 0.3338632750397456

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 12
question Which documents are checked and which biometric modalities are used in France?
seed_nodes 25
expanded_nodes 183
retrieved 169
gold 490
precision 0.03550295857988166
recall 0.012244897959183673
f1 0.018209408194233685

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 13
question Which question topics and biometric modalities are used in France?
seed_nodes 25
expanded_nodes 186
retrieved 174
gold 145
precision 0.034482758620689655
recall 0.041379310344827586
f1 0.03761755485893417

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 14
question Which biometric modalities are used at passport control in France?
seed_nodes 25
expanded_nodes 178
retrieved 163
gold 22
precision 0.024539877300613498
recall 0.18181818181818182
f1 0.043243243243243246

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 15
question Which question topics are asked at passport control in France?
seed_nodes 25
expanded_nodes 322
retrieved 559
gold 127
precision 0.1967799642218247
recall 0.8661417322834646
f1 0.32069970845481055

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 16
question Which documents do I need to bring to passport control in Nice?
seed_nodes 25
expanded_nodes 290
retrieved 523
gold 57
precision 0.1089866156787763
recall 1.0
f1 0.19655172413793107

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 17
question Which documents do I need to bring to passport control in Germany?
seed_nodes 25
expanded_nodes 381
retrieved 1014
gold 822
precision 0.7840236686390533
recall 0.9671532846715328
f1 0.8660130718954249

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 18
question In which city in France are the most documents requested?
seed_nodes 25
expanded_nodes 707
retrieved 509
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 19
question In which country are the fewest documents requested?
seed_nodes 25
expanded_nodes 126
retrieved 124
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 20
question In which country is hotel booking requested most often?
seed_nodes 25
expanded_nodes 405
retrieved 1046
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 21
question In which country is a return ticket requested most often?
seed_nodes 25
expanded_nodes 577
retrieved 1471
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 22
question In which country are people most often asked about money?
seed_nodes 25
expanded_nodes 209
retrieved 174
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 23
question Which question topics are most common at passport control in Germany?
seed_nodes 25
expanded_nodes 354
retrieved 1010
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 24
question How often are fingerprints taken when entering Germany?
seed_nodes 25
expanded_nodes 179
retrieved 170
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 25
question Which airport do people most often fly into in France?
seed_nodes 25
expanded_nodes 1427
retrieved 1454
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 26
question Which city is the most popular entry point into France?
seed_nodes 25
expanded_nodes 731
retrieved 553
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 27
question In which country do travellers most often pass through passport control with no questions asked?
seed_nodes 25
expanded_nodes 680
retrieved 1806
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 28
question Where is passport control usually just a passport check?
seed_nodes 25
expanded_nodes 168
retrieved 116
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 29
question Which documents do I need to bring to passport control in Nice?
seed_nodes 25
expanded_nodes 290
retrieved 523
gold 57
precision 0.1089866156787763
recall 1.0
f1 0.19655172413793107

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 30
question Which documents do I need to bring to passport control in Lyon?
seed_nodes 25
expanded_nodes 272
retrieved 505
gold 47
precision 0.07524752475247524
recall 0.8085106382978723
f1 0.13768115942028986

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 31
question Which documents do I need to bring to passport control in Marseille?
seed_nodes 25
expanded_nodes 271
retrieved 502
gold 19
precision 0.037848605577689244
recall 1.0
f1 0.07293666026871401

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 32
question Which documents do I need to bring to passport control in Toulouse?
seed_nodes 25
expanded_nodes 298
retrieved 499
gold 5
precision 0.01002004008016032
recall 1.0
f1 0.019841269841269844

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 33
question Which documents do I need to bring to passport control in Berlin?
seed_nodes 25
expanded_nodes 375
retrieved 986
gold 189
precision 0.1845841784989858
recall 0.9629629629629629
f1 0.3097872340425532

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 34
question Which documents do I need to bring to passport control in Munich?
seed_nodes 25
expanded_nodes 374
retrieved 1005
gold 156
precision 0.14925373134328357
recall 0.9615384615384616
f1 0.2583979328165374

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 35
question Which documents do I need to bring to passport control in Frankfurt?
seed_nodes 25
expanded_nodes 532
retrieved 1477
gold 151
precision 0.1008801624915369
recall 0.9867549668874173
f1 0.18304668304668306

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 36
question Which documents do I need to bring to passport control in Dusseldorf?
seed_nodes 25
expanded_nodes 524
retrieved 1471
gold 97
precision 0.060503059143439834
recall 0.9175257731958762
f1 0.11352040816326531

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 37
question Which documents do I need to bring to passport control in Stuttgart?
seed_nodes 25
expanded_nodes 331
retrieved 1034
gold 56
precision 0.05415860735009671
recall 1.0
f1 0.10275229357798164

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 38
question Which documents do I need to bring to passport control in Rome?
seed_nodes 25
expanded_nodes 209
retrieved 282
gold 88
precision 0.29432624113475175
recall 0.9431818181818182
f1 0.4486486486486487

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 39
question Which documents do I need to bring to passport control in Milan?
seed_nodes 25
expanded_nodes 356
retrieved 775
gold 31
precision 0.03870967741935484
recall 0.967741935483871
f1 0.07444168734491315

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 40
question Which documents do I need to bring to passport control in Venice?
seed_nodes 25
expanded_nodes 218
retrieved 278
gold 49
precision 0.17625899280575538
recall 1.0
f1 0.2996941896024465

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 41
question Which documents do I need to bring to passport control in Bologna?
seed_nodes 25
expanded_nodes 213
retrieved 278
gold 12
precision 0.04316546762589928
recall 1.0
f1 0.08275862068965519

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 42
question Which documents do I need to bring to passport control in Bari?
seed_nodes 25
expanded_nodes 214
retrieved 274
gold 7
precision 0.021897810218978103
recall 0.8571428571428571
f1 0.04270462633451958

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 43
question Which documents do I need to bring to passport control in Barcelona?
seed_nodes 25
expanded_nodes 308
retrieved 598
gold 28
precision 0.043478260869565216
recall 0.9285714285714286
f1 0.08306709265175719

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 44
question Which documents do I need to bring to passport control in Malaga?
seed_nodes 25
expanded_nodes 427
retrieved 904
gold 9
precision 0.00995575221238938
recall 1.0
f1 0.01971522453450164

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 45
question Which documents do I need to bring to passport control in Madrid?
seed_nodes 25
expanded_nodes 317
retrieved 604
gold 11
precision 0.018211920529801324
recall 1.0
f1 0.03577235772357724

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 46
question Which documents do I need to bring to passport control in Las Palmas?
seed_nodes 25
expanded_nodes 147
retrieved 154
gold 4
precision 0.025974025974025976
recall 1.0
f1 0.05063291139240507

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 47
question Which documents do I need to bring to passport control in Seville?
seed_nodes 25
expanded_nodes 234
retrieved 389
gold 3
precision 0.007712082262210797
recall 1.0
f1 0.015306122448979591

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 48
question Which documents do I need to bring to passport control in Italy?
seed_nodes 25
expanded_nodes 206
retrieved 282
gold 260
precision 0.8794326241134752
recall 0.9538461538461539
f1 0.915129151291513

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 49
question Which documents do I need to bring to passport control in Spain?
seed_nodes 25
expanded_nodes 161
retrieved 149
gold 61
precision 0.3959731543624161
recall 0.9672131147540983
f1 0.5619047619047619

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 50
question In which city in Germany are the most documents requested?
seed_nodes 25
expanded_nodes 1160
retrieved 985
gold 808
precision 0.7928934010152284
recall 0.9665841584158416
f1 0.8711656441717792

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 51
question Which question topics are most common at passport control in Italy?
seed_nodes 25
expanded_nodes 230
retrieved 282
gold 51
precision 0.1702127659574468
recall 0.9411764705882353
f1 0.2882882882882883

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 52
question Which question topics are most common at passport control in Spain?
seed_nodes 25
expanded_nodes 426
retrieved 894
gold 12
precision 0.007829977628635347
recall 0.5833333333333334
f1 0.015452538631346577

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 53
question How often are fingerprints taken when entering Spain?
seed_nodes 25
expanded_nodes 192
retrieved 211
gold 41
precision 0.1848341232227488
recall 0.9512195121951219
f1 0.3095238095238095

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 54
question How often are fingerprints taken when entering Italy?
seed_nodes 25
expanded_nodes 266
retrieved 413
gold 155
precision 0.36561743341404357
recall 0.9741935483870968
f1 0.5316901408450704

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 55
question Which airport do people most often fly into in Italy?
seed_nodes 25
expanded_nodes 403
retrieved 274
gold 149
precision 0.5328467153284672
recall 0.9798657718120806
f1 0.690307328605201

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 56
question Which airport do people most often fly into in Germany?
seed_nodes 25
expanded_nodes 1397
retrieved 1269
gold 433
precision 0.3341213553979511
recall 0.9792147806004619
f1 0.49823736780258515

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 57
question Which airport do people most often fly into in Spain?
seed_nodes 25
expanded_nodes 1263
retrieved 1354
gold 40
precision 0.028064992614475627
recall 0.95
f1 0.054519368723099

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 58
question Which city is the most popular entry point into Germany?
seed_nodes 25
expanded_nodes 1108
retrieved 978
gold 433
precision 0.4335378323108384
recall 0.9792147806004619
f1 0.6009922041105599

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 59
question Which city is the most popular entry point into Italy?
seed_nodes 25
expanded_nodes 404
retrieved 276
gold 149
precision 0.5289855072463768
recall 0.9798657718120806
f1 0.6870588235294117

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 60
question Which city is the most popular entry point into Spain?
seed_nodes 25
expanded_nodes 236
retrieved 246
gold 40
precision 0.15447154471544716
recall 0.95
f1 0.26573426573426573

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 61
question Through which country do travelers most often pass with 'no questions'?
seed_nodes 25
expanded_nodes 317
retrieved 607
gold 1123
precision 0.57166392092257
recall 0.3089937666963491
f1 0.40115606936416187

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 62
question Which is more common in Germany: a request to show cash or a card?
seed_nodes 25
expanded_nodes 405
retrieved 1056
gold 469
precision 0.4327651515151515
recall 0.9744136460554371
f1 0.599344262295082

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 63
question Which is more common in Italy: a request to show cash or a card?
seed_nodes 25
expanded_nodes 500
retrieved 370
gold 154
precision 0.40540540540540543
recall 0.974025974025974
f1 0.5725190839694657

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 64
question In which city in Italy are the most documents requested?
seed_nodes 25
expanded_nodes 413
retrieved 286
gold 260
precision 0.8671328671328671
recall 0.9538461538461539
f1 0.9084249084249084

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 65
question In which city in Spain are the most documents requested?
seed_nodes 25
expanded_nodes 160
retrieved 148
gold 61
precision 0.39864864864864863
recall 0.9672131147540983
f1 0.5645933014354066

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 66
question In which city in France is hotel booking requested most often?
seed_nodes 25
expanded_nodes 691
retrieved 496
gold 62
precision 0.11895161290322581
recall 0.9516129032258065
f1 0.21146953405017924

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 67
question In which city in Germany is hotel booking requested most often?
seed_nodes 25
expanded_nodes 1131
retrieved 978
gold 104
precision 0.10224948875255624
recall 0.9615384615384616
f1 0.18484288354898334

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 68
question In which city in Italy is hotel booking requested most often?
seed_nodes 25
expanded_nodes 432
retrieved 272
gold 42
precision 0.13970588235294118
recall 0.9047619047619048
f1 0.24203821656050953

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 69
question In which city in Spain is hotel booking requested most often?
seed_nodes 25
expanded_nodes 175
retrieved 174
gold 3
precision 0.017241379310344827
recall 1.0
f1 0.03389830508474576

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 70
question In which city in Germany is a return ticket requested most often?
seed_nodes 25
expanded_nodes 1139
retrieved 984
gold 284
precision 0.2815040650406504
recall 0.9753521126760564
f1 0.4369085173501578

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 71
question In which city in Italy is a return ticket requested most often?
seed_nodes 25
expanded_nodes 418
retrieved 272
gold 53
precision 0.17279411764705882
recall 0.8867924528301887
f1 0.2892307692307692

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 72
question In which city in Spain is a return ticket requested most often?
seed_nodes 25
expanded_nodes 162
retrieved 131
gold 6
precision 0.04580152671755725
recall 1.0
f1 0.0875912408759124

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 73
question In which country are people most often requested to show hotel booking?
seed_nodes 25
expanded_nodes 219
retrieved 188
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 74
question In which city in France are people most often requested to show hotel booking?
seed_nodes 25
expanded_nodes 706
retrieved 496
gold 62
precision 0.11895161290322581
recall 0.9516129032258065
f1 0.21146953405017924

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 75
question In which city in Germany are people most often requested to show accommodation booking?
seed_nodes 25
expanded_nodes 1159
retrieved 978
gold 104
precision 0.10224948875255624
recall 0.9615384615384616
f1 0.18484288354898334

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 76
question In which city in Italy are people most often requested to show hotel booking?
seed_nodes 25
expanded_nodes 437
retrieved 272
gold 42
precision 0.13970588235294118
recall 0.9047619047619048
f1 0.24203821656050953

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 77
question In which city in Spain are people most often requested to show hotel booking?
seed_nodes 25
expanded_nodes 172
retrieved 115
gold 3
precision 0.02608695652173913
recall 1.0
f1 0.05084745762711864

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 78
question In which country are people most often asked about money?
seed_nodes 25
expanded_nodes 209
retrieved 174
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 79
question In which city in France are people most often asked about money?
seed_nodes 25
expanded_nodes 791
retrieved 616
gold 19
precision 0.024350649350649352
recall 0.7894736842105263
f1 0.047244094488188976

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 80
question In which city in Germany are people most often asked about money?
seed_nodes 25
expanded_nodes 1188
retrieved 1059
gold 31
precision 0.028328611898016998
recall 0.967741935483871
f1 0.05504587155963303

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 81
question In which city in Spain are people most often asked about money?
seed_nodes 25
expanded_nodes 270
retrieved 215
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 82
question In which city in Italy are people most often asked about money?
seed_nodes 25
expanded_nodes 424
retrieved 272
gold 18
precision 0.0625
recall 0.9444444444444444
f1 0.11724137931034483

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 83
question Where is passport control most often limited to only the passport?
seed_nodes 25
expanded_nodes 373
retrieved 784
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 84
question Which is more common in France: a request to show cash or a card?
seed_nodes 25
expanded_nodes 335
retrieved 616
gold 14
precision 0.017857142857142856
recall 0.7857142857142857
f1 0.034920634920634915

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 85
question Which is more common in Spain: a request to show cash or a card?
seed_nodes 25
expanded_nodes 231
retrieved 234
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 86
question In which country are visas requested most often at passport control?
seed_nodes 25
expanded_nodes 621
retrieved 1746
gold 59
precision 0.032073310423825885
recall 0.9491525423728814
f1 0.06204986149584487

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 87
question In which city in Germany are hotel bookings requested most often?
seed_nodes 25
expanded_nodes 1125
retrieved 978
gold 104
precision 0.10224948875255624
recall 0.9615384615384616
f1 0.18484288354898334

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 88
question In which airport in France are return tickets requested most often?
seed_nodes 25
expanded_nodes 887
retrieved 1071
gold 125
precision 0.10830999066293184
recall 0.928
f1 0.1939799331103679

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 89
question In which country are travelers most often asked about visit duration?
seed_nodes 25
expanded_nodes 184
retrieved 164
gold 162
precision 0.5182926829268293
recall 0.5246913580246914
f1 0.5214723926380369

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 90
question In which country are fingerprints checked most often at passport control?
seed_nodes 25
expanded_nodes 167
retrieved 161
gold 22
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 91
question In which city in Italy is face photo capture used most often?
seed_nodes 25
expanded_nodes 403
retrieved 278
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 92
question Which country has the highest number of encounters with no questions asked?
seed_nodes 25
expanded_nodes 626
retrieved 1743
gold 1123
precision 0.5668387837062536
recall 0.8797862867319679
f1 0.6894626657362177

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 93
question In which country is passport-only control (no questions, only foreign passport) most common?
seed_nodes 25
expanded_nodes 173
retrieved 123
gold 0
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 94
question Which country has the highest number of document checks per encounter?
seed_nodes 25
expanded_nodes 169
retrieved 124
gold 1611
precision 0.8064516129032258
recall 0.06207324643078833
f1 0.11527377521613831

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 95
question Which city in Italy has the highest number of question topics per encounter?
seed_nodes 25
expanded_nodes 659
retrieved 1250
gold 47
precision 0.0352
recall 0.9361702127659575
f1 0.06784888203546646

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 96
question Which city in Germany has more encounters with visa checks than with return ticket checks?
seed_nodes 25
expanded_nodes 405
retrieved 978
gold 296
precision 0.2955010224948875
recall 0.9763513513513513
f1 0.4536891679748823

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 97
question What documents are checked and what question topics are asked in Madrid?
seed_nodes 25
expanded_nodes 343
retrieved 622
gold 11
precision 0.017684887459807074
recall 1.0
f1 0.03475513428120063

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 98
question Which documents are checked in Rome but not in Barcelona?
seed_nodes 25
expanded_nodes 148
retrieved 102
gold 96
precision 0.0
recall 0.0
f1 0.0

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 99
question Which documents are checked for travelers who were asked about visit_purpose in Spain?
seed_nodes 25
expanded_nodes 649
retrieved 1806
gold 5
precision 0.0011074197120708748
recall 0.4
f1 0.0022087244616234123

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 100
question Which question topics are asked for travelers whose documents include return_ticket in France?
seed_nodes 25
expanded_nodes 354
retrieved 545
gold 79
precision 0.11926605504587157
recall 0.8227848101265823
f1 0.20833333333333331

Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=16, offset=111>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 111, 'line': 4, 'column': 16}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n        CALL db.index.vector.queryNodes($index_name, $k, $embedding)\n        YIELD node, score\n        RETURN id(node) AS nid, labels(node) AS labels, node.key AS key, score\n        '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=2, column=21, offset=21>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 21, 'line': 2, 'column': 21}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=4, column=29, offset=96>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 96, 'line': 4, 'column': 29}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (s) WHERE id(s) IN $seed_ids\n    MATCH p=(s)-[*0..2]-(n)\n    RETURN collect(DISTINCT id(n)) AS node_ids\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N02', status_description='warn: feature deprecated without replacement. id is deprecated and will be removed without a replacement.', position=<SummaryInputPosition line=3, column=11, offset=35>, raw_classification='DEPRECATION', classification=<NotificationClassification.DEPRECATION: 'DEPRECATION'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'DEPRECATION', '_severity': 'WARNING', '_position': {'offset': 35, 'line': 3, 'column': 11}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `documentType` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=10, column=27, offset=331>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 331, 'line': 10, 'column': 27}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `topicKey` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=13, column=26, offset=435>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 435, 'line': 13, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '
Received notification from DBMS server: <GqlStatusObject gql_status='01N51', status_description='warn: relationship type does not exist. The relationship type `biometricModality` does not exist. Verify that the spelling is correct.', position=<SummaryInputPosition line=16, column=26, offset=541>, raw_classification='UNRECOGNIZED', classification=<NotificationClassification.UNRECOGNIZED: 'UNRECOGNIZED'>, raw_severity='WARNING', severity=<NotificationSeverity.WARNING: 'WARNING'>, diagnostic_record={'_classification': 'UNRECOGNIZED', '_severity': 'WARNING', '_position': {'offset': 541, 'line': 16, 'column': 26}, 'OPERATION': '', 'OPERATION_CODE': '0', 'CURRENT_SCHEMA': '/'}> for query: '\n    MATCH (e:Encounter)\n    WHERE id(e) IN $node_ids\n\n    OPTIONAL MATCH (e)-[:atCountry]->(co:Country)\n    OPTIONAL MATCH (e)-[:atCity]->(ci:City)\n    OPTIONAL MATCH (e)-[:atAirport]->(ap:Airport)\n\n    OPTIONAL MATCH (e)-[:hasDocumentCheck]->(:DocumentCheck)-[:requestedDocument]->(di:DocumentInstance)\n    OPTIONAL MATCH (di)-[:documentType]->(dt)\n\n    OPTIONAL MATCH (e)-[:hasQuestioning]->(q:Questioning)\n    OPTIONAL MATCH (q)-[:topicKey]->(tk)\n\n    OPTIONAL MATCH (e)-[:hasBiometricCheck]->(b:BiometricCheck)\n    OPTIONAL MATCH (b)-[:biometricModality]->(bm)\n\n    RETURN e.key AS encounter_key,\n           collect(DISTINCT co.key) AS countries,\n           collect(DISTINCT ci.key) AS cities,\n           collect(DISTINCT ap.key) AS airports,\n           collect(DISTINCT coalesce(dt.key, di.documentType)) AS docs,\n           collect(DISTINCT coalesce(tk.key, q.topicKey)) AS topics,\n           collect(DISTINCT coalesce(bm.key, b.biometricModality)) AS bios\n    '

qnum 101
question Show document checks and biometric modalities for the same encounters in Germany.
seed_nodes 25
expanded_nodes 385
retrieved 1028
gold 25
precision 0.0048638132295719845
recall 0.2
f1 0.00949667616334283
saved_csv = /Users/i.sharganov/🟩🟩🟩/обучение/МАГА/мага_обучение/3_сем/Диплом/эксперимент/neo4j_граф/retrieval_outputs/node_embedding_baseline_f1.csv
n_questions = 101
mean_f1 = 0.22542728295085093
median_f1 = 0.11527377521613831

     qnum        f1
0       1  0.701754
1       2  0.923547
2       3  0.320700
3       4  0.138016
4       5  0.320988
..    ...       ...
96     97  0.034755
97     98  0.000000
98     99  0.002209
99    100  0.208333
100   101  0.009497

[101 rows x 2 columns]

In [66]:
k

NameError: name 'k' is not defined

In [68]:
result_df.head(100)

    qnum        f1
0      1  0.701754
1      2  0.923547
2      3  0.320700
3      4  0.138016
4      5  0.320988
..   ...       ...
95    96  0.453689
96    97  0.034755
97    98  0.000000
98    99  0.002209
99   100  0.208333

[100 rows x 2 columns]